---

- name: nginx
  gather_facts: false
  hosts: all
  vars:
    ansible_user: debian
  become: yes
  tasks:
  
  - name: Install Nginx
    apt:
      name: nginx
      state: latest   
      update_cache: yes 
    