---
- name: clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
- name: vector
  src: git@github.com:nikefeel/vector-role.git
  scm: git
  version: "1.2"
- name: lighthouse
  src: git@github.com:nikefeel/lighthouse-role.git
  scm: git
  version: "1.1"