apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
spec:
  selector:
    app: multitool
  ports:
    - protocol: TCP
      port: 1180
      targetPort: 1180
