apiVersion: v1
kind: Service
metadata:
  name: netology-web
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
