apiVersion: v1
kind: Service
metadata:
  name: multi-node
spec:
  type: NodePort
  selector:
    app: multi
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
      nodePort: 30002
